name: Notify on Commit

on:
  push:
    branches:
      - '**'

jobs:
  reload-bot-config:
    runs-on: ubuntu-latest
    steps:
      - name: Sends a GET request to the API to reload its config
        run: |
          curl -G "${{ secrets.ENDPOINT_URL }}" \
            -H "X-API-Key: ${{ secrets.API_KEY }}"
